### ISSUE TITLE
Issue: embeds not working

### ISSUE THREAD

**Issue by fonsecagabriella** [trigaten/Learn_Prompting#1019] opened 2023-07-24 10:40 UTC
Embeds keep returning error for the API key, although the key is valid (tested on other applications, works fine).

<img width="1253" alt="Screenshot 2023-07-24 at 12 36 49" src="https://github.com/trigaten/Learn_Prompting/assets/1550446/48c7e186-88c2-4bcb-846e-b5f480023efe">

**Comment by trigaten** [comment] 2023-07-24 11:21
Can you inspect element and send me the error in terminal? I cannot reproduce this problem. Can you also try a new key?

**Comment by fonsecagabriella** [comment] 2023-07-24 18:48
I tried in different browsers too (Chrome, Firefox, Safari)

**Comment by trigaten** [comment] 2023-07-24 19:10
I believe this is related to only some people having access to gpt-4, looking into this further.

**Comment by trigaten** [comment] 2023-07-24 19:18
I found that the error was caused by the embed verifying API keys by checking if the user had access to the first model in the MODELS list, which happened to be gpt-4. Since not everyone had access, it only failed for some people.


I have pushed a fix, thank you very much!

**Closed by trigaten** 2023-07-24 19:18 UTC
